FROM node:16.3.0-slim

LABEL version="1.0"
LABEL description="This is the base docker image for Loving Sitters client side"

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install --production

COPY . .

EXPOSE 3000

CMD ["npm","start"]