version: '3'

services:
  server:
    env_file: './server/.env'
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'server'
    ports:
      - '3001:3001'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'client'
    ports:
      - '3000:3000'
    links:
      - server
